### ISSUE TITLE
ModuleNotFoundError: No module named 'masonite.facades'

### ISSUE THREAD

**Issue by richarddewit** [MasoniteFramework/dashboard#8]
After a clean install (and some minor tinkering, nothing crucial) I've installed masonite-dashboard (with the appropriate configuration). But then the auto-reload gave this error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/richard/dev/python/.virtualenvs/mymasonite-lL8UhgyT/lib/python3.7/site-packages/hupper/ipc.py", line 318, in spawn_main
    func(**kwargs)
  File "/home/richard/dev/python/.virtualenvs/mymasonite-lL8UhgyT/lib/python3.7/site-packages/hupper/worker.py", line 263, in worker_main
    func(*spec_args, **spec_kwargs)
  File "/home/richard/dev/python/.virtualenvs/mymasonite-lL8UhgyT/lib/python3.7/site-packages/masonite/commands/_devserver.py", line 129, in run
    wsgi_handler = _import_application(module_name, app_name)
  File "/home/richard/dev/python/.virtualenvs/mymasonite-lL8UhgyT/lib/python3.7/site-packages/masonite/commands/_devserver.py", line 122, in _import_application
    module = import_module(module_name)
  File "/home/richard/dev/python/.virtualenvs/mymasonite-lL8UhgyT/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/richard/dev/python/mymasonite/wsgi.py", line 33, in <module>
    located_provider.load_app(container).register()
  File "/home/richard/dev/python/.virtualenvs/mymasonite-lL8UhgyT/lib/python3.7/site-packages/masonite/providers/AppProvider.py", line 33, in register
    from routes import web
  File "/home/richard/dev/python/mymasonite/routes/web.py", line 3, in <module>
    from dashboard.routes import routes as DashboardRoutes
  File "/home/richard/dev/python/.virtualenvs/mymasonite-lL8UhgyT/lib/python3.7/site-packages/dashboard/routes.py", line 3, in <module>
    from dashboard.controllers.UserManagementController import UserManagementController
  File "/home/richard/dev/python/.virtualenvs/mymasonite-lL8UhgyT/lib/python3.7/site-packages/dashboard/controllers/UserManagementController.py", line 2, in <module>
    from masonite.facades.Auth import Auth
ModuleNotFoundError: No module named 'masonite.facades'
```

And now when I run `craft serve`, I get:

```
$ craft serve
Loading .env environment variables…

WARNING: No module named 'masonite.facades'

  [CommandNotFound]                
  Command "serve" is not defined.
```

Output of `craft info`:

```
$ craft info
Loading .env environment variables…

Environment Information
-------------------------  ------------------
System Information         Linux x86_64 64bit
System Memory              16 GB
Python Version             CPython 3.7.3
Virtual Environment        ✓
Masonite Version           2.2.5
Craft Version              2.1.2
APP_ENV                    local
APP_DEBUG                  True
```

I get the idea that `masonite-dashboard` isn't compatible with newer versions of Masonite.

**Comment by vman26** [comment]
Dashboard is not working with version 2.2.8 either.

**Comment by josephmancuso** [comment]
Yes Masonite dashboard is a bit of an abandoned project from me at least. I’d be open to having someone maintain it though.

**Comment by vman26** [comment]
Even though it is in a abandoned state, isn't it better to leave this issue one open.

Reason for this issue is legit and this way people can see what the issue is and come up with a solution or accept it as an real issue. By closing it it looks like everything is just "fine".

But that's my personal opinion.
